### ISSUE TITLE
Synapse wont execute scripts.

### ISSUE THREAD

**Issue by garrows69** [3dsboy08/Synapse-Issues#14] opened 2017-09-16 14:24 UTC
After I execute Dex synapse wont execute anything, not even print()

**Comment by ehsaan555** [comment] 2017-09-17 12:06
Try closing your browser - it happened to me once, and I closed my browser and it worked.

**Comment by 3dsboy08** [comment] 2017-09-18 00:34
Can't reproduce.

If anyone else has the issue, contact me.

**Comment by garrows69** [comment] 2017-09-18 00:38
I am using this version of Dex.
[DexExplorer.txt](https://github.com/3dsboy08/Synapse-Issues/files/1309496/DexExplorer.txt)
After I execute and it loads I cant execute anything from Synapse. I try print() and warn(). No output

**Closed** 2017-10-07 18:01 UTC
